import {S,$,esc,pretty,icon,heading,note,warning,badge,field,textarea,select,options,button,modal,closeModal,toast} from './ui.js';
import {sourceDisplayMap,sourceOriginalRange} from './source-model.js';
import {sourceOriginButton} from './source-view.js';

let gdSelected=null,gdFilter='all',gdPending=null,gdSequence=0;
const gdUid=()=>crypto.randomUUID?.()??Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const gdButton=(label,action,attrs='',primary=false)=>`<button type="button" class="button ${primary?'primary':''}" data-grounding="${esc(action)}" ${attrs}>${label}</button>`;
const gdBase=()=>`/cases/${encodeURIComponent(S.current.case.id)}/grounding`;
const gdCurrent=stamp=>stamp.caseId===S.current?.case.id&&stamp.epoch===S.epoch;
const gdStamp=()=>({caseId:S.current.case.id,epoch:S.epoch,expected_revision:S.current.case.revision,expected_review_revision:S.grounding?.review_revision??0});
const gdData=()=>`data-case-id="${esc(S.current.case.id)}" data-case-revision="${S.current.case.revision}" data-review-revision="${S.grounding.review_revision}"`;
const gdContext=form=>({expected_revision:Number(form.dataset.caseRevision),expected_review_revision:Number(form.dataset.reviewRevision)});
const gdSave=label=>`<div class="form-actions"><button type="submit" class="button primary">${label}</button></div>`;
const gdLabel=r=>r.kind==='identity'?'Identity mention':'Deadline wording';
const gdInstant=v=>{
 if(!v)return 'Not set';
 const parts=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}:\d{2})/.exec(v);
 if(!parts)return v;
 const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
 const offset=/([+-]\d{2}:\d{2}|Z)$/.exec(v)?.[1]??'';
 return `${parts[3]} ${months[Number(parts[2])-1]} ${parts[1]} · ${parts[4]} ${offset==='Z'||offset==='+00:00'?'UTC':'UTC'+offset}`;
};
function gdSurrounding(r,src){
 if(!src)return '';
 const chars=Array.from(src.text),start=Math.max(0,r.mention.start-220),end=Math.min(chars.length,r.mention.end+220);
 const before=chars.slice(start,r.mention.start).join(''),selected=chars.slice(r.mention.start,r.mention.end).join(''),after=chars.slice(r.mention.end,end).join('');
 if(selected!==r.mention.quote)return '';
 return `<details class="gd-context" open><summary>Surrounding source context</summary><p>${start?'…':''}${esc(before)}<mark>${esc(selected)}</mark>${esc(after)}${end<chars.length?'…':''}</p><small>Original excerpt characters ${start}:${end}. Keep negation and attribution in view.</small></details>`;
}
export function clearGrounding(){gdSequence++;gdSelected=null;gdFilter='all';gdPending=null;S.grounding=null;}
export async function loadGrounding(api){const stamp=gdStamp(),seq=++gdSequence;const view=await api(gdBase());if(gdCurrent(stamp)&&seq===gdSequence)S.grounding=view;}
function gdRecord(){const rows=S.grounding?.records??[];return rows.find(r=>r.id===gdSelected)??rows.find(r=>gdFilter==='all'||(gdFilter==='attention'?r.needs_attention:r.kind===gdFilter));}
const gdWarning=w=>({source_needs_review:'Source must be reviewed before relying on this interpretation.',source_unavailable_or_retracted:'Supporting source is unavailable or retracted. Reconsider this judgement; any adopted deadline remains in force until explicitly changed.',actor_record_changed:'The linked actor record changed. Review the identity judgement against the current record.',deadline_has_subsequently_changed:'The live deadline changed after this interpretation. This is historical context, not the current schedule.',deadline_target_removed:'The former target is no longer in the live graph.'}[w]??pretty(w));
function gdInspector(r){if(!r)return `<div class="gd-empty"><span class="empty-symbol">${icon('search')}</span><h2>Clarity begins with the source.</h2><p>Select an exact name or date phrase. Record your interpretation without rewriting the words it came from.</p>${gdButton('Select source wording','new','',true)}</div>`;
 const identity=r.kind==='identity';const source=S.grounding.sources.find(s=>s.id===r.mention.evidence_id);
 return `<div class="gd-inspector"><header><div><span class="kicker">${gdLabel(r).toUpperCase()} / SOURCE-ANCHORED</span><h2>${esc(r.mention.quote)}</h2></div>${badge(r.needs_attention?'time_sensitive':r.status==='applied'?'reported':'unknown',r.needs_attention?'Re-review required':pretty(r.status))}</header>
 <section class="gd-quote"><div class="meta"><span class="kicker">EXACT SOURCE WORDING</span>${badge(source?.status??'retracted')}</div><blockquote>${esc(r.mention.quote)}</blockquote>${gdSurrounding(r,source)}<div><strong>${esc(r.source_title)}</strong><p>${esc(r.source_attribution)}</p><small class="mono">Characters ${r.mention.start}:${r.mention.end} · SHA ${esc(r.mention.content_sha256.slice(0,14))}…</small></div><div class="spacer"></div>${sourceOriginButton(r.mention.evidence_id)}</section>
 ${r.warnings.map(w=>warning(gdWarning(w))).join('')}
 <section class="gd-meaning"><span class="kicker">REVIEW QUESTION</span><p>${esc(r.note)}</p>${r.reason!==r.note?`<h3>Latest reviewer rationale</h3><p>${esc(r.reason)}</p>`:''}</section>
 ${identity?`<section><div class="section-title"><h2>Possible matching records</h2><small>Text matches, not identity proof</small></div><div class="gd-candidates">${r.candidates.map(a=>`<article><div class="gd-avatar">${esc(a.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</div><div><h3>${esc(a.name)}</h3><p>${esc(a.role||'Role not recorded')}</p><small>${esc(a.id)} · ${a.match==='same_name_text'?'Same name text':'Shared name words'}</small></div></article>`).join('')||note('No matching name tokens. You can choose another existing actor or leave the mention unresolved.')}</div>${r.actor_id?`<div class="gd-judgement"><strong>${r.status==='distinct'?'Explicitly distinguished from':'Last recorded actor'}: ${esc(r.actor_name??r.actor_id)}</strong><p>This judgement concerns this quotation only. Other records and actor relationships are unchanged.</p></div>`:''}<div class="toolbar">${gdButton('Review identity','identity','',true)}${button('Add an actor separately','add-actor')}</div></section>`:
 `<section><div class="section-title"><h2>Deadline interpretation</h2><small>Nothing is scheduled by a quotation alone</small></div>${r.application?`<div class="gd-date-result"><div><span class="kicker">ADOPTED LOCAL TIME</span><strong>${esc(gdInstant(r.application.local))}</strong><small>${esc(r.application.time_zone)}</small></div><div><span class="kicker">STORED IN UTC</span><strong>${esc(gdInstant(r.application.utc))}</strong><small>Applied at case revision ${r.application.applied_revision}</small></div></div>${note('Previous value: '+gdInstant(r.application.before))}`:note('Choose the calendar date, wall-clock time and timezone deliberately. “Tomorrow” needs the source’s reference date, not the import date.')}<div class="toolbar">${gdButton(r.application?'Review another interpretation':'Interpret & preview timing','deadline','',true)}</div></section>`}
 <section class="gd-history"><div class="section-title"><h2>Interpretation history</h2><small>${r.history.length} preserved entries</small></div>${r.history.slice().reverse().map(h=>`<div><span class="kicker">${esc(pretty(h.operation))} · CASE REV ${h.case_revision}</span><p>${esc(gdInstant(h.recorded_at))} · ${esc(h.actor)}</p><p>${esc(pretty(h.disposition))}${h.actor_name?' · '+esc(h.actor_name):''}: ${esc(h.reason)}</p></div>`).join('')}<div class="toolbar">${gdButton(r.status==='dismissed'?'Reopen review':'Dismiss, keep history','disposition',`data-disposition="${r.status==='dismissed'?'open':'dismissed'}"`)}</div></section></div>`;
}
export function groundingPage(){const v=S.grounding;if(!v)return heading('SOURCE CLARITY','Identity & deadline review.','Loading the source-linked interpretation record.');
 const rows=v.records.filter(r=>gdFilter==='all'||(gdFilter==='attention'?r.needs_attention:r.kind===gdFilter));const r=gdRecord();gdSelected=r?.id??null;
 return heading('SOURCE CLARITY / HUMAN JUDGEMENT','Resolve the meaning. Keep the evidence.','Names are not identities. Relative dates are not deadlines. Make the interpretation explicit before it affects the operation.',gdButton('Select source wording','new','',true))+`<div class="gd-summary"><div><strong>${v.records.filter(r=>r.kind==='identity').length}</strong><span>Identity mentions</span></div><div><strong>${v.records.filter(r=>r.kind==='deadline').length}</strong><span>Deadline reviews</span></div><div><strong>${v.needs_attention}</strong><span>Need reconsideration</span></div><div><strong>Source → Review → Apply</strong><span>No automatic merges or schedule edits</span></div></div><div class="gd-layout"><aside class="gd-queue"><header><span class="kicker">INTERPRETATION RECORDS</span><div class="gd-filters">${[['all','All'],['identity','People'],['deadline','Dates'],['attention','Attention']].map(([k,t])=>`<button type="button" data-grounding="filter" data-id="${k}" class="${gdFilter===k?'active':''}" aria-pressed="${gdFilter===k}">${t}</button>`).join('')}</div></header><div>${rows.map(x=>`<button type="button" class="gd-item ${x.id===gdSelected?'selected':''}" data-grounding="select" data-id="${esc(x.id)}" aria-pressed="${x.id===gdSelected}"><span class="kicker">${gdLabel(x)}</span><h3>${esc(x.mention.quote)}</h3><p>${esc(x.source_title)}</p>${badge(x.needs_attention?'time_sensitive':'reported',x.needs_attention?'Needs attention':pretty(x.status))}</button>`).join('')||`<div class="panel-body">${note('No review records in this view. Start with an exact source phrase.')}</div>`}</div></aside><section class="panel gd-main">${gdInspector(r)}</section><aside class="gd-principles"><span class="kicker">GUARDRAILS</span><h3>Interpretation is a judgement.</h3><p>Link one mention. Keep every actor record. Do not infer authority from a matching name.</p><div class="divider"></div><h3>Preview before scheduling.</h3><p>A deadline change names its source, timezone and target. You see its route impact before applying it.</p><div class="divider"></div><h3>History does not disappear.</h3><p>Retractions and later edits flag earlier interpretations. They never silently undo an adopted deadline.</p><div class="divider"></div>${note('No AI model is called by these controls. Fictional development cases only.')}</aside></div>`;
}
function gdTargets(){const c=S.current.case;return [['case|'+c.id,'Overall case deadline'],...c.graph.conditions.map(x=>['condition|'+x.id,'Condition: '+x.title]),...c.decisions.map(x=>['decision|'+x.id,'Decision: '+x.question]),...c.questions.map(x=>['question|'+x.id,'Question: '+x.question])];}
function gdSetReader(){const form=$('form[data-grounding-form="new"]');if(!form)return;const src=S.grounding.sources.find(x=>x.id===form.elements.evidence_id.value);$('#gd-reader').value=src?sourceDisplayMap(src.text).text:'';}
function gdBasis(){const form=$('form[data-grounding-form="deadline"]');if(!form)return;const relative=form.elements.basis.value==='relative_days';for(const node of form.querySelectorAll('[data-gd-basis]')){const shown=(node.dataset.gdBasis==='relative')===relative;node.hidden=!shown;for(const el of node.querySelectorAll('input'))el.disabled=!shown;}}
function gdDeadlineForm(r){const app=r.application,base=app?.basis;gdPending=null;modal('Interpret the source timing',`<div class="gd-dialog-quote"><span class="kicker">SOURCE WORDING</span><p>${esc(r.mention.quote)}</p><small>${esc(r.source_title)}</small></div><form data-grounding-form="deadline" data-id="${esc(r.id)}" ${gdData()}><div class="form-grid"><div class="full">${select('Where does this deadline apply?','target',gdTargets(),app?app.target.kind+'|'+app.target.id:'case|'+S.current.case.id)}</div><div class="full">${select('How is the date established?','basis',[['absolute','Explicit calendar date'],['relative_days','Relative to a source reference date']],base?.basis??'absolute')}</div><div data-gd-basis="absolute" class="full">${field('Exact calendar date, not an ambiguous day/month string','calendar_date',base?.calendar_date??'','date','required')}</div><div data-gd-basis="relative" class="full"><div class="form-grid">${field('Reference date established from the source','anchor_date',base?.anchor_date??'','date','required')}${field('Calendar days after reference date (tomorrow = 1)','day_offset',base?.day_offset??1,'number','required min="-366" max="366"')}<div class="full">${field('Why is this the correct reference date?','anchor_reason',base?.anchor_reason??'','text','required minlength="3" maxlength="1000"')}</div></div></div>${field('Local wall-clock time, 24-hour','wall_time',base?.wall_time??'','time','required')}${field('IANA timezone or UTC','time_zone',base?.time_zone??'','text','required placeholder="Europe/London" maxlength="80"')}<div class="full">${field('How was this timezone established?','zone_reason',base?.zone_reason??'','text','required minlength="3" maxlength="1000" placeholder="Explicitly stated in source, or separately confirmed…"')}</div><div class="full">${select('Repeated clock time only: which occurrence?','fold',[['','No occurrence chosen'],['0','First occurrence (earlier instant)'],['1','Second occurrence (later instant)']],base?.fold===null||base?.fold===undefined?'':String(base.fold))}</div><div class="full">${textarea('Why does this reading apply to the selected target?','reason',r.reason,'required minlength="3" maxlength="2000"')}</div></div>${gdSave('Preview deadline change')}</form><div id="gd-preview"></div>`,true);gdBasis();}
function gdPreviewHTML(p){const r=p.resolution;if(!p.can_apply)return warning(r.status==='ambiguous'?'This clock time occurs twice. Choose the first or second occurrence above, then preview again.':'This local time does not exist because the clock moves forward. Clarify the source; do not silently shift the deadline.')+r.options.map(o=>`<p class="note">${o.fold===0?'First':'Second'} occurrence: ${esc(o.local)} → ${esc(o.utc)}</p>`).join('');
 return `<section class="gd-preview"><span class="kicker">REVIEW THE SCHEDULE AMENDMENT</span><h3>${esc(p.target_title)}</h3><div class="gd-date-result"><div><small>Current deadline</small><strong>${esc(gdInstant(p.before))}</strong></div><div><small>Proposed local date and time</small><strong>${esc(gdInstant(r.selected.local))}</strong><small>${esc(r.time_zone)}</small></div></div><p class="note">UTC instant: ${esc(r.selected.utc)}. ${p.approvals_to_invalidate} approval(s) will be invalidated.</p><p class="note">Routes exceeding constraints: ${p.route_summary.constraint_failures_before} before → ${p.route_summary.constraint_failures_after} after.</p><p class="note">This applies one deadline only. It does not confirm the source claim, change an actor or mark work complete.</p><div class="form-actions">${gdButton('Apply this reviewed deadline','apply-deadline','',true)}</div></section>`;
}
export function bindGrounding({api,render,refreshCases}){
 document.addEventListener('change',e=>{if(e.target.matches('[data-gd-source]'))gdSetReader();if(e.target.matches('form[data-grounding-form="deadline"] [name="basis"]'))gdBasis();});
 document.addEventListener('input',e=>{if(e.target.closest('form[data-grounding-form="deadline"]')){gdPending=null;if($('#gd-preview'))$('#gd-preview').innerHTML=note('Details changed. Preview again before applying.');}});
 document.addEventListener('change',e=>{if(e.target.closest('form[data-grounding-form="deadline"]')){gdPending=null;if($('#gd-preview'))$('#gd-preview').innerHTML=note('Details changed. Preview again before applying.');}});
 document.addEventListener('click',async e=>{const el=e.target.closest('[data-grounding]');if(!el)return;try{const action=el.dataset.grounding;
  if(action==='select'){gdSelected=el.dataset.id;render();return;}
  if(action==='filter'){gdFilter=el.dataset.id;gdSelected=null;render();return;}
  if(action==='new'){const srcs=S.grounding.sources.filter(x=>x.status!=='retracted');modal('Select exactly what needs interpretation',note('Highlight the name or date wording in a source. Its original characters and location are retained. Import longer documents through Source Desk first.')+`<form data-grounding-form="new" ${gdData()}>${select('Source evidence','evidence_id',[['','Choose source evidence'],...srcs.map(s=>[s.id,s.title+' · '+s.status])],'','required data-gd-source')}<label class="field"><span>Select a phrase in the original excerpt</span><textarea id="gd-reader" class="gd-reader" readonly spellcheck="false"></textarea></label>${select('What needs clarification?','kind',[['identity','Who does this name refer to?'],['deadline','What exact deadline does this mean?']])}${textarea('What needs review, and why?','note','','required minlength="3" maxlength="2000"')}${gdSave('Create source-linked review')}</form>`,true);gdSetReader();return;}
  if(action==='apply-deadline'){const pending=gdPending;if(!pending||!gdCurrent(pending))throw new Error('The preview is no longer current. Preview again.');el.disabled=true;try{pending.event_id??=gdUid();const result=await api(`/cases/${pending.caseId}/grounding/deadline-apply`,{...pending.request,event_id:pending.event_id,preview_digest:pending.preview.preview_digest});if(!gdCurrent(pending))return;S.current={case:result.case,plan:result.plan,briefing:result.briefing,changes:result.changes};S.grounding=result.reviews;S.history=null;S.selectedRoutes.clear();gdPending=null;await refreshCases();if(!gdCurrent(pending))return;closeModal();render();toast('Deadline applied and routes recalculated. No factual condition was attested.');}finally{if(el.isConnected)el.disabled=false;}return;}
  const row=gdRecord();if(!row)throw new Error('Select an interpretation first.');
  if(action==='deadline'){gdDeadlineForm(row);return;}
  if(action==='identity'){modal('Resolve this identity mention',warning('This records your judgement about one quotation. It does not merge people, infer authority or rewrite previous references.','neutral')+`<blockquote>${esc(row.mention.quote)}</blockquote><form data-grounding-form="identity" data-id="${esc(row.id)}" ${gdData()}>${select('Review decision','disposition',[['linked','This mention refers to the selected actor'],['distinct','This mention is NOT the selected actor'],['unresolved','Identity remains unresolved']],['linked','distinct','unresolved'].includes(row.status)?row.status:'unresolved')}${select('Existing actor (unused for unresolved)','actor_id',[['','Choose an actor'],...S.current.case.actors.map(a=>[a.id,a.name+' · '+(a.role||'Role not recorded')+' ['+a.id+']'])],row.actor_id??'')}${textarea('Evidence and reasoning for this judgement','reason','','required minlength="3" maxlength="2000"')}${gdSave('Record judgement, preserve records')}</form>`);return;}
  if(action==='disposition'){modal(el.dataset.disposition==='open'?'Reopen interpretation':'Dismiss without deleting',note('All previous decisions stay in history. This does not undo an already applied deadline or merge any records.')+`<form data-grounding-form="disposition" data-id="${esc(row.id)}" data-disposition="${esc(el.dataset.disposition)}" ${gdData()}>${textarea('Reason','reason','','required minlength="3" maxlength="2000"')}${gdSave('Record review decision')}</form>`);}
 }catch(err){toast(err.message,true);}});
 document.addEventListener('submit',async e=>{const form=e.target;if(!form.dataset.groundingForm)return;e.preventDefault();const submit=form.querySelector('[type=submit]');const stamp={caseId:form.dataset.caseId,epoch:S.epoch};submit.disabled=true;try{if(!gdCurrent(stamp))throw new Error('The selected case changed. Reopen this form.');const fd=new FormData(form),v=Object.fromEntries(fd),ctx=gdContext(form);let data,path;
  if(form.dataset.groundingForm==='deadline'){const [kind,id]=v.target.split('|');const interpretation={basis:v.basis,wall_time:v.wall_time,time_zone:v.time_zone,zone_reason:v.zone_reason,fold:v.fold===''?null:Number(v.fold)};if(v.basis==='absolute')interpretation.calendar_date=v.calendar_date;else Object.assign(interpretation,{anchor_date:v.anchor_date,day_offset:Number(v.day_offset),anchor_reason:v.anchor_reason});const request={...ctx,review_id:form.dataset.id,interpretation,target:{kind,id},reason:v.reason};const preview=await api(`/cases/${stamp.caseId}/grounding/deadline-preview`,request);if(!gdCurrent(stamp)||!form.isConnected)return;gdPending=preview.can_apply?{...stamp,request,preview}:null;$('#gd-preview').innerHTML=gdPreviewHTML(preview);$('#gd-preview').scrollIntoView({block:'nearest'});return;}
  form.dataset.eventId??=gdUid();data={...ctx,event_id:form.dataset.eventId};
  if(form.dataset.groundingForm==='new'){const src=S.grounding.sources.find(s=>s.id===v.evidence_id);if(!src)throw new Error('Choose a source first.');const reader=$('#gd-reader'),range=sourceOriginalRange(src.text,0,reader.selectionStart,reader.selectionEnd);const quote=Array.from(src.text).slice(range.start,range.end).join('');if(Array.from(quote).length>2000)throw new Error('Choose a short phrase, up to 2,000 Unicode characters.');data={...data,kind:v.kind,note:v.note,mention:{evidence_id:src.id,...range,quote,content_sha256:src.content_sha256}};path='create';}
  else if(form.dataset.groundingForm==='identity'){data={...data,review_id:form.dataset.id,disposition:v.disposition,actor_id:v.disposition==='unresolved'?null:v.actor_id||null,reason:v.reason};path='identity';}
  else{data={...data,review_id:form.dataset.id,disposition:form.dataset.disposition,reason:v.reason};path='disposition';}
  const result=await api(`/cases/${stamp.caseId}/grounding/${path}`,data);if(!gdCurrent(stamp))return;S.grounding=result;gdSelected=path==='create'?result.records[0]?.id:form.dataset.id;gdFilter='all';closeModal();render();toast('Interpretation history saved. Case facts and planning state are unchanged.');
 }catch(err){toast(err.message,true);}finally{if(submit.isConnected)submit.disabled=false;}});
}
