// Framework-free browser client. Every persisted change goes through the authenticated API.
const $ = (selector) => document.querySelector(selector);
const h = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eventId = () => globalThis.crypto.randomUUID ? globalThis.crypto.randomUUID() : Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)), b=>b.toString(16).padStart(2,'0')).join('');
const pretty = value => String(value).replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());
const money = n => new Intl.NumberFormat('en-GB', {style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const duration = n => n < 60 ? `${n} min` : `${Number((n / 60).toFixed(1))} hrs`;
const date = value => new Date(value).toLocaleString('en-GB', {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const localDate = value => { const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset()*60000).toISOString().slice(0,16); };
const pill = (value, label) => `<span class="pill ${h(value)}">${h(label || pretty(value))}</span>`;
const btn = (label, act, primary=false, extra='') => `<button class="button ${primary?'primary':''}" data-act="${h(act)}" ${extra}>${label}</button>`;
let token = ''; try { token = sessionStorage.getItem('8ball.token') || ''; } catch {}
const state = {cases:[], current:null, tab:'command', changes:null, audit:null, advice:null, busy:false};
let toastTimer, priorFocus, openSequence = 0;
function toast(text, error=false) { const el=$('#toast'); el.textContent=text; el.className='visible'+(error?' error':''); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.className='',6000); }
function setToken(value) { token=value; try { if(value)sessionStorage.setItem('8ball.token',value);else sessionStorage.removeItem('8ball.token'); } catch {} }
async function api(path, body) {
  const r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await r.json();
  if(!r.ok) { if(r.status===401){setToken('');render();} const detail=typeof data.detail==='string'?data.detail:'The server rejected an invalid field. Check the form and try again.'; throw new Error(detail); }
  return data;
}
async function refreshCases() { state.cases=await api('/cases'); }
async function openCase(id,tab='room') { const seq=++openSequence; const result=await api('/cases/'+encodeURIComponent(id)); if(seq!==openSequence)return; state.current=result; state.tab=tab;state.changes=null;state.audit=null;state.advice=null;render(); }
async function command(kind,payload) {
  if(state.busy)return;
  const c=state.current.case;state.busy=true;$('#app').classList.add('busy');
  try {
    const data=await api(`/cases/${c.id}/events`,{event_id:eventId(),expected_revision:c.revision,kind,payload});
    state.current=data;state.changes=data.changes;state.audit=null;state.advice=null;await refreshCases();closeModal();render();toast('Saved. Routes and dependencies recalculated.');
  } catch(e) { toast(e.message,true); } finally { state.busy=false;$('#app').classList.remove('busy'); }
}
function closeModal(){ $('#modal-root').innerHTML=''; if(priorFocus?.isConnected)priorFocus.focus(); }
function modal(title,content,wide=false){priorFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="backdrop"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${h(title)}"><div class="modal-head"><h2>${h(title)}</h2><button class="close" aria-label="Close dialog" data-act="close">×</button></div><div class="modal-content">${content}</div></section></div>`;setTimeout(()=>$('.modal input,.modal textarea,.modal select,.modal button')?.focus(),0);}
function field(label,name,value='',type='text',extra=''){return `<label class="form-field"><span class="label-text">${h(label)}</span><input name="${h(name)}" type="${type}" value="${h(value)}" ${extra}></label>`;}
function download(filename,value,type='application/json'){const blob=new Blob([type==='application/json'?JSON.stringify(value,null,2):value],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const conditionTitle=id=>state.current.case.graph.conditions.find(c=>c.id===id)?.title||id;
const actionTitle=id=>state.current.case.graph.actions.find(a=>a.id===id)?.title||id;
const nav=[['command','◫','Agency command'],['room','◎','Situation room'],['graph','⌘','Outcome graph'],['routes','⇢','Ways through'],['evidence','▤','Evidence'],['actions','✓','Actions & approvals'],['audit','◷','Decision trail'],['client','◇','Client brief']];
function render(){
  if(!token){$('#app').innerHTML=`<div class="login"><div class="login-copy"><div class="brand"><span class="ball">8</span>8BALL</div><p class="eyebrow space">SITUATION INTELLIGENCE</p><h1>Every situation.<br>A <em>way through.</em></h1><p>Understand what happened. Define what needs to become true. Build the route between the two.</p></div><div class="login-panel"><span class="eyebrow">LOCAL OPERATOR WORKSPACE</span><div class="space"></div><h2>Step into the situation room.</h2><p>Start the local server with <code>python -m eightball</code>, then paste the operator token printed in your terminal.</p><form id="login-form">${field('Operator token','token','','password','required minlength="32" autocomplete="off"')}<button class="button primary" type="submit">Open workspace <span>↗</span></button></form><div class="divider"></div><p class="note">Local alpha · Fictional or test cases only.<br>No live AI runs automatically. No external actions are sent.</p></div></div>`;return;}
  if(!state.current && state.tab!=='command')state.tab='command';
  const c=state.current?.case;
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="ball">8</span>8BALL</div><div class="workspace"><span>Emotive Impact</span><span>⌄</span></div><span class="eyebrow">WORKSPACE</span><nav class="nav" aria-label="Workspace">${nav.filter(x=>c||x[0]==='command').map(([id,icon,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}" ${state.tab===id?'aria-current="page"':''}><span>${icon}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><p class="model-state"><span class="dot"></span>Deterministic engine active</p><p class="note">AI is optional. People approve.<br>Evidence determines the state.</p><button class="text-button" data-act="signout">Lock workspace ↗</button></div></aside><div class="main-shell"><header class="topbar"><div class="crumb">Workspace <span class="muted"> / </span> <strong>${h(nav.find(n=>n[0]===state.tab)?.[2])}</strong></div><div class="topright"><span class="pill">LOCAL ALPHA · TEST DATA</span><span class="avatar">EI</span></div></header><main>${page()}<footer class="page-footer"><span>8BALL / OUTCOME ENGINEERING</span><span>Human-led. Evidence-backed. No guaranteed outcomes.</span></footer></main></div></div>`;
}
function heading(eyebrow,title,sub,buttons=''){return `<div class="page-heading"><div><span class="eyebrow">${h(eyebrow)}</span><h1>${h(title)}</h1><p>${h(sub)}</p></div><div class="buttons">${buttons}</div></div>`;}
function page(){switch(state.tab){case'command':return commandPage();case'room':return roomPage();case'graph':return graphPage();case'routes':return routesPage();case'evidence':return evidencePage();case'actions':return actionsPage();case'audit':return auditPage();case'client':return clientPage();}}
function commandPage(){return heading('AGENCY COMMAND','Clarity. Then action.','A working view of your situations, their outcomes and what needs to happen next.',btn('＋ New situation','new',true))+
  `<div class="stats"><div class="stat"><div class="number">${state.cases.length}</div><small>Situations in this workspace</small></div><div class="stat"><div class="number">${state.cases.filter(c=>new Date(c.deadline)<new Date()).length}</div><small>Deadlines elapsed</small></div><div class="stat"><div class="number">${state.cases.reduce((a,c)=>a+c.revision,0)}</div><small>Recorded case updates</small></div><div class="stat"><div class="number">Human</div><small>Authority for every decision</small></div></div>`+
  (state.cases.length?`<div class="case-grid">${state.cases.map(c=>`<button class="case-card" data-open-case="${h(c.id)}"><div class="meta-line"><span class="eyebrow">${h(c.client)}</span><span>↗</span></div><h2>${h(c.title)}</h2><p>${h(c.desired_outcome)}</p><div class="meta-line"><small>Deadline ${date(c.deadline)}</small><span class="pill">REV ${c.revision}</span></div></button>`).join('')}</div>`:`<div class="panel empty"><span class="ball">8</span><h2>Start with a situation.</h2><p>Open a fictional client-retention case to explore real planning, evidence review and scenario changes. Or bring your own test situation.</p><div class="buttons">${btn('Open fictional case ↗','demo',true)}${btn('Create test situation','new')}</div><p class="note">No generated success percentages. No messages sent on your behalf.</p></div>`);}
function stats(p){const best=p.routes[0];return `<div class="stats"><div class="stat"><div class="number">${p.routes.length}</div><small>Candidate routes</small></div><div class="stat"><div class="number">${Object.values(p.states).filter(x=>x.status==='true').length}<small> / ${Object.keys(p.states).length}</small></div><small>Conditions evidenced</small></div><div class="stat"><div class="number">${Object.values(p.action_states).filter(x=>x.status==='ready').length}</div><small>Actions ready now</small></div><div class="stat"><div class="number">${best?duration(best.minutes):'—'}</div><small>Leading route · optimistic estimate</small></div></div>`;}
function changeBanner(){const ch=state.changes;if(!ch)return '';return `<div class="warning good"><strong>Situation updated.</strong> ${ch.duplicate?'This update was already recorded.':`${ch.conditions.length} condition change(s). ${ch.newly_ready.length} action(s) newly ready. ${ch.no_longer_ready.length} no longer ready. ${ch.constraint_failures_after} route(s) now exceed a constraint.`}</div>`;}
function roomPage(){const {case:c,plan:p}=state.current;const best=p.routes[0];return heading('SITUATION / '+c.id.slice(0,8).toUpperCase(),c.title,c.client,btn('What if?','simulate')+btn('Find a way through ↗','ways',true))+
  changeBanner()+`<div class="outcome"><div class="target">◎</div><div><span class="eyebrow">DESIRED OUTCOME</span><h2>${h(c.desired_outcome)}</h2><p>${p.outcome_evidenced?'Outcome supported by reviewed-source observations. Review residual risks before closure.':'Work backwards from what must become true. An intended result is not a verified fact.'}</p></div></div>`+stats(p)+
  `<div class="columns"><div class="stack"><section class="panel"><div class="panel-head"><h2>What must become true</h2><button class="text-button" data-tab="graph">Explore graph ↗</button></div>${c.graph.conditions.map((cond,i)=>`<div class="row"><div class="flex"><span class="index mono">${String(i+1).padStart(2,'0')}</span><div><button class="label text-button" data-condition="${h(cond.id)}">${h(cond.title)}</button><p>${h(cond.confirmation)}</p></div></div>${pill(p.states[cond.id].status)}</div>`).join('')}</section><section class="panel"><div class="panel-head"><h2>Situation brief</h2><span class="pill">OPERATOR PROVIDED</span></div><div class="panel-body"><p class="case-summary muted">${h(c.summary)}</p></div></section></div><div class="stack">${best?routeCard(best,0):''}<section class="panel"><div class="panel-head"><h2>Move next</h2><span class="pill">HUMAN LED</span></div>${nextActions(p)}</section><section class="panel"><div class="panel-head"><h3>Operating constraints</h3><button class="text-button" data-act="constraints">Edit ↗</button></div><div class="row"><small>Outcome deadline</small><span class="mono">${date(c.deadline)}</span></div><div class="row"><small>Total case budget</small><span class="mono">${money(c.budget)}</span></div></section></div></div>`;}
function nextActions(p){const actions=state.current.case.graph.actions.filter(a=>['ready','approval_required'].includes(p.action_states[a.id].status)).slice(0,4);return actions.length?actions.map(a=>`<div class="row"><div><h3>${h(a.title)}</h3><p>${h(a.owner)} · ${duration(a.minutes)}</p></div><button class="text-button" data-tab="actions">${p.action_states[a.id].status==='ready'?'View ↗':'Review ↗'}</button></div>`).join(''):`<div class="panel-body"><p class="note">Verify the outstanding conditions or reconcile disputed observations before progressing.</p></div>`;}
function routeCard(r,i){return `<article class="route-card ${i===0?'first':''}"><div class="route-top"><span class="eyebrow">ROUTE ${String(i+1).padStart(2,'0')}${i===0?' / FIRST BY RULES':''}</span>${pill(r.status,r.breaches.length?'Constraint failure':r.blocked?'Needs evidence':'Conditional')}</div><h3>${h(r.title)}</h3><div class="route-metrics"><div><strong>${duration(r.minutes)}</strong><small>Optimistic estimate</small></div><div><strong>${money(r.total_cost)}</strong><small>Total estimated cost</small></div></div><div class="route-note">${r.breaches.length?h(r.breaches.join('. ')):r.unverified.length?'Verification needed: '+r.unverified.map(conditionTitle).map(h).join(', '):`${r.actions.length} actions · ${r.contingent.length} third-party-dependent step(s).`}<br>Not a prediction of success.</div>${btn('Inspect route ↗','route',false,`data-id="${h(r.id)}"`)}</article>`;}
function routesPage(){const p=state.current.plan;return heading('PATH ANALYSIS','More than one way through.','Compare dependencies, constraints and the conditions each route relies on.',btn('Test a scenario','simulate')+btn('Edit constraints','constraints'))+
 `<div class="warning">${h(p.ranking)} ${p.search_truncated?'Search limit reached: candidates are incomplete.':''}<br>Durations exclude unverified inputs and third-party waiting. These are conditional plans, not forecasts.</div><div class="route-list">${p.routes.map(routeCard).join('')}</div>`;}
function graphPage(){const {case:c}=state.current;const nodes=[],positions={};const depths={};const condDepth=id=>{if(depths[id]!==undefined)return depths[id];const producers=c.graph.actions.filter(a=>a.produces.includes(id));depths[id]=producers.length?Math.max(...producers.map(a=>a.requires.length?Math.max(...a.requires.map(condDepth))+2:1))+1:0;return depths[id];};c.graph.conditions.forEach(x=>condDepth(x.id));c.graph.conditions.forEach(x=>nodes.push({key:'c_'+x.id,id:x.id,title:x.title,depth:depths[x.id],type:'condition'}));c.graph.actions.forEach(a=>nodes.push({key:'a_'+a.id,id:a.id,title:a.title,depth:a.requires.length?Math.max(...a.requires.map(condDepth))+1:0,type:'action'}));const rows={};nodes.forEach(n=>{const row=rows[n.depth]||0;positions[n.key]={x:n.depth*218+15,y:row*108+20};rows[n.depth]=row+1;});const width=(Math.max(...nodes.map(n=>n.depth))+1)*218+20,height=Math.max(...Object.values(rows))*108+45;const links=[];c.graph.actions.forEach(a=>{a.requires.forEach(id=>links.push(['c_'+id,'a_'+a.id]));a.produces.forEach(id=>links.push(['a_'+a.id,'c_'+id]));});const svg=`<svg class="graph" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" aria-label="Outcome dependency graph">${links.map(([from,to])=>{const a=positions[from],b=positions[to];return `<path class="graph-line" d="M ${a.x+184} ${a.y+35} C ${a.x+201} ${a.y+35},${b.x-17} ${b.y+35},${b.x} ${b.y+35}"/>`;}).join('')}${nodes.map(n=>{const pos=positions[n.key],st=n.type==='condition'?state.current.plan.states[n.id].status:'action';const words=n.title.split(' '),lines=[''];words.forEach(w=>{if((lines.at(-1)+' '+w).length>24)lines.push(w);else lines[lines.length-1]+=(lines.at(-1)?' ':'')+w;});return `<g class="graph-group" tabindex="0" role="button" aria-label="${h(n.title)}" ${n.type==='condition'?`data-condition="${h(n.id)}"`:'data-tab="actions"'}><rect x="${pos.x}" y="${pos.y}" width="184" height="78" rx="7" class="graph-node ${st}"/><text x="${pos.x+12}" y="${pos.y+17}" class="graph-small">${n.type==='condition'?h(pretty(st)):'ACTION'}</text>${lines.slice(0,2).map((line,i)=>`<text x="${pos.x+12}" y="${pos.y+38+i*16}" class="graph-label">${h(line)}</text>`).join('')}</g>`;}).join('')}</svg>`;return heading('OUTCOME GRAPH','See what unlocks what.','Conditions are evidenced states. Actions propose transitions. Click a condition to inspect or attest it.',btn('Edit outcome graph','edit-graph'))+`<div class="panel"><div class="panel-head"><h3>${c.graph.conditions.length} conditions · ${c.graph.actions.length} actions</h3><span class="pill">SCROLL TO EXPLORE →</span></div><div class="graph-scroll">${svg}</div></div><div class="space"></div><p class="note">Edges show human-authored prerequisites and expected effects, not proven causal relationships. Unknown inputs never count as established facts.</p>`;}
function evidencePage(){const c=state.current.case;return heading('EVIDENCE & OBSERVATIONS','Establish what is true.','Review a source first. Then explicitly record which condition it supports or contradicts.',btn('＋ Add evidence','add-evidence',true))+
 `<div class="warning">A reviewed source is not automatically a verified fact. Conflicting active observations stay disputed until explicitly reconciled.</div><div class="columns"><div class="evidence-list">${c.evidence.length?c.evidence.map(e=>`<article class="panel evidence-card"><div class="meta-line"><h3>${h(e.title)}</h3>${pill(e.status)}</div><p class="tag">${h(e.source)} · ${date(e.added_at)}</p><div class="source-text">${h(e.text)}</div><div class="buttons">${e.status==='unreviewed'?btn('Mark source reviewed','review-source',true,`data-id="${h(e.id)}"`):''}${e.status==='reviewed'?btn('Record an observation','observe'):''}${e.status!=='retracted'?btn('Retract source','retract-source',false,`data-id="${h(e.id)}"`):''}</div></article>`).join(''):`<div class="panel empty"><h2>No evidence yet.</h2><p>Add a source excerpt with its provenance. Source text is never treated as an instruction to the system.</p>${btn('Add first source','add-evidence',true)}</div>`}</div><div class="stack"><section class="panel"><div class="panel-head"><h2>Optional model assistance</h2><span class="pill">ADVISORY ONLY</span></div><div class="panel-body"><p class="note">GLiClass classifies locally. Jev uses TypeSafe’s API. Ollama proposes source-linked observations. No model verifies facts or changes this case.</p><div class="space"></div><form id="advice-form"><label class="label-text">Source<select name="evidence_id" required><option value="">Select evidence</option>${c.evidence.filter(e=>e.status!=='retracted').map(e=>`<option value="${h(e.id)}">${h(e.title)}</option>`).join('')}</select></label><label class="label-text">Provider<select name="provider"><option value="gliclass">GLiClass Edge · local classification</option><option value="jev">Jev · external classification</option><option value="ollama">Ollama · local source extraction</option></select></label><label class="check"><input type="checkbox" name="allow_external"><span>I authorise sending this source excerpt to TypeSafe when Jev is selected.</span></label><div class="space"></div><button class="button" type="submit">Request model assistance ↗</button></form>${state.advice?`<pre class="advice">${h(JSON.stringify(state.advice,null,2))}</pre>`:''}<div class="divider"></div><p class="note">Models must be installed or configured first. Failure falls back to manual review, not invented output.</p></div></section><section class="panel"><div class="panel-head"><h2>Observed conditions</h2><button class="text-button" data-act="observe">Add ↗</button></div>${c.observations.length?c.observations.slice().reverse().map(o=>`<div class="row"><div><h3>${h(conditionTitle(o.condition_id))}</h3><p>${h(o.rationale)}</p><small>Statement: ${o.value?'true':'false'} · ${o.supersedes.length} superseded</small></div></div>`).join(''):`<div class="panel-body"><p class="note">None recorded. Task completion alone cannot create an observation.</p></div>`}</section></div></div>`;}
function actionsPage(){const {case:c,plan:p}=state.current;const order={ready:0,approval_required:1,blocked:2,completed:3};const acts=c.graph.actions.slice().sort((a,b)=>order[p.action_states[a.id].status]-order[p.action_states[b.id].status]);return heading('EXECUTION & APPROVALS','The next move matters.','These controls record human work. They do not send messages, spend money or contact anyone.',btn('Record observation','observe'))+
 `<div class="panel">${acts.map(a=>{const s=p.action_states[a.id];return `<div class="row"><div class="grow"><div class="meta-line"><h3>${h(a.title)}</h3>${pill(s.status)}</div><p>${h(a.owner)} · ${duration(a.minutes)} · ${money(a.cost)} estimated · ${h(a.risk)} operator-rated risk</p><p>${h(a.purpose)}${a.contingent?' · Result depends on another party; confirmation required.':''}</p><p>${s.missing.length?'Needs: '+s.missing.map(conditionTitle).map(h).join(' / '):'Prerequisites are evidenced.'}${s.status==='completed'&&!s.effects_verified?' Work recorded, intended result still unverified.':''}</p></div><div class="row-actions">${s.status==='approval_required'?btn('Review & approve','approve',true,`data-id="${h(a.id)}"`):''}${s.status==='ready'?btn('Record completion','complete',false,`data-id="${h(a.id)}"`):''}</div></div>`;}).join('')}</div>`;}
function auditPage(){const a=state.audit;return heading('DECISION TRAIL','A record of every change.','Local application-level audit chain. Not certified evidence custody or protection against an administrator rewriting the database.',btn('Export complete case','export'))+
 (a?`<div class="warning ${a.valid?'good':''}">${a.valid?'Hash chain and latest snapshot verified.':'Audit verification failed. Investigate before relying on this record.'} ${a.events.length} recorded events.</div><div class="panel"><div class="panel-body"><div class="timeline">${a.events.slice().reverse().map(e=>`<div class="timeline-entry"><span class="eyebrow">REV ${e.revision} / ${date(e.recorded_at)}</span><h3>${h(pretty(e.kind))}</h3><p>Recorded by ${h(e.actor)}</p><p class="mono">${h(e.hash)}</p><details><summary class="note">View recorded payload</summary><pre class="advice">${h(JSON.stringify(e.payload,null,2))}</pre></details></div>`).join('')}</div></div></div>`:`<div class="panel empty"><p>Load and verify the complete event chain.</p>${btn('Verify decision trail','audit-load',true)}</div>`);}
function clientPage(){const c=state.current.case,p=state.current.plan;return heading('CLIENT BRIEF / OPERATOR PREVIEW','A clear picture. Not the noise.','This is a preview for the operator, not an authenticated client portal or a shared link.',btn('Export brief','brief-export'))+`<div class="outcome"><div class="target">◎</div><div><span class="eyebrow">YOUR OUTCOME</span><h2>${h(c.desired_outcome)}</h2><p>${p.outcome_evidenced?'Outcome evidenced. Residual risks need review.':'Your team is working through the required conditions.'}</p></div></div><div class="panel"><div class="panel-head"><h2>${h(c.title)}</h2>${pill('unknown',p.outcome_evidenced?'Outcome evidenced':'In progress')}</div><div class="row"><span>Work recorded as complete</span><strong>${c.completed.length} action(s)</strong></div><div class="row"><span>Conditions supported by evidence</span><strong>${Object.values(p.states).filter(s=>s.status==='true').length}</strong></div><div class="row"><span>Target deadline</span><strong>${date(c.deadline)}</strong></div><div class="panel-body"><p class="note">This view omits internal evidence excerpts and deliberations. A human must review any exported brief before sharing it.</p></div></div>`;}
function observationModal(condition='') {const c=state.current.case,reviewed=c.evidence.filter(e=>e.status==='reviewed');modal('Record an evidence-backed observation',`<p class="note">Attest only what this source actually supports. This changes the live case and invalidates previous approvals. Opposite active observations become disputed.</p><form id="observe-form"><div class="form-grid"><label class="form-field full"><span class="label-text">Condition</span><select name="condition_id">${c.graph.conditions.map(x=>`<option value="${h(x.id)}" ${x.id===condition?'selected':''}>${h(x.title)} (${h(state.current.plan.states[x.id].status)})</option>`).join('')}</select></label><label class="form-field full"><span class="label-text">Reviewed source</span><select name="evidence_id" required><option value="">Select a reviewed source</option>${reviewed.map(e=>`<option value="${h(e.id)}">${h(e.title)}</option>`).join('')}</select></label><label class="form-field"><span class="label-text">This condition is</span><select name="value"><option value="true">True, supported by this source</option><option value="false">False, contradicted by this source</option></select></label>${field('Why does the source support this?','rationale','','text','required maxlength="180"')}<label class="check full"><input type="checkbox" name="supersede"><span>Explicitly replace earlier observations of this condition. They remain in the audit record.</span></label></div>${!reviewed.length?'<p class="warning">Add and review a source before recording an observation.</p>':''}<div class="form-actions"><button class="button primary" type="submit" ${!reviewed.length?'disabled':''}>Attest & recalculate</button></div></form>`);}
function newModal(){modal('Open a new test situation',`<p class="note">Choose an explicit starter playbook. The initial graph is a human-authored template, not AI analysis of your description. Customise it afterwards.</p><form id="case-form"><div class="form-grid">${field('Situation title','title','','text','required maxlength="180"')}${field('Client / organisation','client','','text','required maxlength="180"')}<label class="form-field full"><span class="label-text">What happened?</span><textarea name="summary" required maxlength="12000"></textarea></label><div class="full">${field('Desired outcome','desired_outcome','','text','required maxlength="180"')}</div><label class="form-field"><span class="label-text">Starter playbook</span><select name="template"><option value="retention">Commercial client retention</option><option value="recovery">Service recovery</option></select></label>${field('Budget (whole GBP)','budget',7000,'number','required min="0" max="100000000"')}${field('Outcome deadline','deadline',localDate(new Date(Date.now()+24*3600000)),'datetime-local','required')}</div><div class="form-actions"><button class="button primary" type="submit">Create situation ↗</button></div></form>`);}
function scenarioModal(){const c=state.current.case;modal('What changes if…',`<p class="warning">Sandbox only. Nothing here changes the live case or its audit trail. A scenario is an assumption, not a forecast.</p><form id="scenario-form"><div class="form-grid">${field('Hypothetical deadline','deadline',localDate(c.deadline),'datetime-local','required')}${field('Hypothetical budget (GBP)','budget',c.budget,'number','required min="0" max="100000000"')}<label class="form-field"><span class="label-text">Change one condition (optional)</span><select name="condition"><option value="">Keep current evidence state</option>${c.graph.conditions.map(x=>`<option value="${h(x.id)}">${h(x.title)}</option>`).join('')}</select></label><label class="form-field"><span class="label-text">Assume it becomes</span><select name="value"><option value="false">False</option><option value="true">True</option></select></label></div><div class="form-actions"><button class="button primary" type="submit">Compare routes ↗</button></div></form>`);}
async function act(name,el){const c=state.current?.case;switch(name){case'close':closeModal();break;case'signout':setToken('');state.current=null;state.cases=[];render();break;case'demo':{const made=await api('/demo',{});await refreshCases();await openCase(made.id);break;}case'new':newModal();break;case'ways':state.tab='routes';render();break;case'simulate':scenarioModal();break;case'constraints':modal('Set operating constraints',`<p class="note">Budget includes completed work plus estimated remaining spend. Saving invalidates existing approvals.</p><form id="constraints-form"><div class="form-grid">${field('Outcome deadline','deadline',localDate(c.deadline),'datetime-local','required')}${field('Total case budget (GBP)','budget',c.budget,'number','required min="0" max="100000000"')}</div><div class="form-actions"><button class="button primary" type="submit">Save & replan</button></div></form>`);break;
case'add-evidence':modal('Add evidence',`<form id="evidence-form"><div class="form-grid">${field('Source title','title','','text','required maxlength="180"')}${field('Provenance / source','source','','text','required maxlength="180"')}<label class="form-field full"><span class="label-text">Exact source text or clearly attributed notes</span><textarea name="text" required maxlength="12000" placeholder="Paste the source excerpt. It will begin as unreviewed."></textarea></label></div><p class="note">Text only in this alpha. Do not paste real confidential case data.</p><div class="form-actions"><button class="button primary" type="submit">Add unreviewed source</button></div></form>`);break;
case'review-source':case'retract-source':{const status=name==='review-source'?'reviewed':'retracted';modal(status==='reviewed'?'Confirm source review':'Retract this source',`<p>${status==='reviewed'?'Mark this source as reviewed? This records your review, not that every statement in the source is true.':'Retract this source? Its observations will stop supporting the live state. The source and history remain preserved.'}</p><div class="form-actions">${btn('Confirm','confirm-source',true,`data-id="${h(el.dataset.id)}" data-status="${status}"`)}</div>`);break;}
case'confirm-source':await command('review_evidence',{evidence_id:el.dataset.id,status:el.dataset.status});break;
case'observe':observationModal();break;case'approve':case'complete':{const a=c.graph.actions.find(x=>x.id===el.dataset.id);modal(name==='approve'?'Approve this specific action':'Record human completion',`<h3>${h(a.title)}</h3><p class="note">${h(a.purpose)}</p><p>${name==='approve'?'Approval is tied to the current case revision. This does not contact anyone or execute the action.':'Record that this work was completed outside 8BALL. This does not establish that its intended result occurred. Add a separate evidence-backed observation for that.'}</p><div class="form-actions">${btn(name==='approve'?'Approve action':'Record completion','confirm-action',true,`data-id="${h(a.id)}" data-kind="${name}"`)}</div>`);break;}
case'confirm-action':await command(el.dataset.kind,{action_id:el.dataset.id});break;
case'route':{const r=state.current.plan.routes.find(r=>r.id===el.dataset.id);modal(r.title,`<p class="warning">Conditional route. ${h(state.current.plan.limits)}</p><div class="route-metrics"><div><strong>${duration(r.minutes)}</strong><small>Optimistic remaining time</small></div><div><strong>${money(r.total_cost)}</strong><small>Total estimated cost</small></div><div><strong>${r.slack_minutes>=0?'+':''}${duration(Math.abs(r.slack_minutes))}</strong><small>${r.slack_minutes<0?'Beyond deadline':'Estimated deadline slack'}</small></div></div><div class="space"></div><div class="panel">${r.schedule.map((s,i)=>`<div class="row"><span class="index">${i+1}</span><div class="grow"><h3>${h(actionTitle(s.action_id))}</h3><p>Starts +${duration(s.start_minute)} · Ends +${duration(s.end_minute)}</p></div>${pill(state.current.plan.action_states[s.action_id].status)}</div>`).join('')}</div><p class="note">${r.unverified.length?'Unverified inputs: '+r.unverified.map(conditionTitle).map(h).join(', '):'All unsatisfied conditions have proposed producers. Expected effects still need evidence.'}</p>`,true);break;}
case'edit-graph':modal('Edit the outcome graph',`<p class="note">Advanced editor. Conditions, goals and actions are validated for missing references and cycles. Existing observed conditions and completed actions cannot be redefined. Estimates and causal assumptions remain your responsibility.</p><form id="graph-form"><label class="label-text">Graph JSON<textarea class="code-editor" name="graph" spellcheck="false" required>${h(JSON.stringify(c.graph,null,2))}</textarea></label><div class="form-actions"><button class="button primary" type="submit">Validate & save graph</button></div></form>`,true);break;
case'audit-load':state.audit=await api(`/cases/${c.id}/export`);render();break;case'export':{const out=await api(`/cases/${c.id}/export`);download(`8BALL-${c.id.slice(0,8)}.json`,out);toast('Case exported with its audit history. Handle the file as sensitive.');break;}
case'brief-export':download(`8BALL-brief-${c.id.slice(0,8)}.txt`,`8BALL CLIENT BRIEF\n${c.title}\n\nDesired outcome: ${c.desired_outcome}\nStatus: ${state.current.plan.outcome_evidenced?'Outcome evidenced; residual risks require review':'In progress'}\nCompleted work: ${c.completed.length} action(s)\nTarget deadline: ${date(c.deadline)}\n\nOperator preview. Human review required before sharing. No guaranteed outcome.\n`,'text/plain');break;}}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-act],[data-tab],[data-open-case],[data-condition]');if(!el)return;try{if(el.dataset.tab){state.tab=el.dataset.tab;state.audit=null;render();}else if(el.dataset.openCase)await openCase(el.dataset.openCase);else if(el.dataset.condition)observationModal(el.dataset.condition);else await act(el.dataset.act,el);}catch(err){toast(err.message,true);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Enter'&&e.target.classList?.contains('graph-group'))e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));if(e.key==='Tab'&&$('.modal')){const items=[...$('.modal').querySelectorAll('button:not([disabled]),a,input:not([disabled]),textarea,select,summary')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.addEventListener('submit',async e=>{const form=e.target;if(!form.id)return;e.preventDefault();const values=Object.fromEntries(new FormData(form));const submit=form.querySelector('[type=submit]');if(submit)submit.disabled=true;try{switch(form.id){case'login-form':setToken(values.token);await refreshCases();render();break;case'case-form':{const made=await api('/cases',{...values,budget:Number(values.budget),deadline:new Date(values.deadline).toISOString()});await refreshCases();closeModal();await openCase(made.id);break;}case'evidence-form':await command('add_evidence',values);break;case'constraints-form':await command('constraints',{budget:Number(values.budget),deadline:new Date(values.deadline).toISOString()});break;case'observe-form':await command('observe',{condition_id:values.condition_id,evidence_id:values.evidence_id,value:values.value==='true',rationale:values.rationale,supersedes:values.supersede?state.current.case.observations.filter(o=>o.condition_id===values.condition_id).map(o=>o.id):[]});break;case'graph-form':await command('replace_graph',{graph:JSON.parse(values.graph)});break;case'advice-form':{state.advice=await api(`/cases/${state.current.case.id}/advice`,{evidence_id:values.evidence_id,provider:values.provider,allow_external:!!values.allow_external});render();toast('Model suggestion received. No case facts or approvals changed.');break;}case'scenario-form':{const before=state.current.plan;const result=await api(`/cases/${state.current.case.id}/simulate`,{expected_revision:state.current.case.revision,budget:Number(values.budget),deadline:new Date(values.deadline).toISOString(),conditions:values.condition?{[values.condition]:values.value==='true'}:{}});modal('Scenario comparison',`<p class="warning">SANDBOX · No case changes saved. Based on revision ${result.base_revision}. All results are conditional on the hypothetical input.</p><div class="scenario-comparison"><div class="panel"><span class="eyebrow">LIVE CASE</span><h3>${before.routes.length} route(s)</h3><p class="note">${before.routes.filter(r=>r.breaches.length).length} constraint failures</p></div><div class="panel"><span class="eyebrow">HYPOTHETICAL CASE</span><h3>${result.plan.routes.length} route(s)</h3><p class="note">${result.plan.routes.filter(r=>r.breaches.length).length} constraint failures</p></div></div>${result.plan.routes.map(r=>`<div class="row"><div><h3>${h(r.title)}</h3><p>${duration(r.minutes)} · ${money(r.total_cost)}</p><p>${h(r.breaches.join('. '))}</p></div>${pill(r.status)}</div>`).join('')}`,true);break;}}}catch(err){toast(err.message,true);}finally{if(submit?.isConnected)submit.disabled=false;}});
render();if(token)refreshCases().then(render).catch(e=>toast(e.message,true));
